### ISSUE TITLE
Grame freezes

### ISSUE THREAD

**Issue by FromTheGrayve** [gwdevhub/Daybreak#696] opened 2024-04-28 01:49 UTC
Just starting using this after returning and found this great tool, but having a bug/crash issue:

Using Toolbox and uMod through Daybreak

My issue is sometimes, when in combat, using the Action: Attack/Interact/Do It keybind cause the game to hang. It seems to only happen with Focus Mode on, but there doesn't seem to be report. Windows event viewer just says "The program Gw.exe version 1.0.0.1 stopped interacting with Windows and was closed. "

Sometimes it hangs right at the start of a fight, other times it won't be for hours and then suddenly in a fight it hangs. 
It doesn't seem to have the issue in towns or interacting with items/npcs, just in combat.

(I was also unable to save build templates due to the documents folder being write only. I have fixed that, but mentioning it in case Daybreak was trying to save something in combat and that caused the hang)

**Comment by AlexMacocian** [comment] 2024-04-28 04:01
Hey, thanks for the detailed report. Sadly this is known issue that I've been trying to fix for some time now but due to how randomly it happens, it's super hard to track down. 

If the game runs fine without Focus View, I'd run it without for now.

*Detailed description below*
Daybreak uses GWCA (a core component of toolbox) for an injectable plugin. GWCA had a heavy rework recently and we're still ironing out issues both in GWCA and in the plugin Daybreak uses.

I've been trying to fix a particular edge case where transferring data between the game thread and the plugin thread results in a memory violation. That's the main source of crashes in Daybreak + Focus View right now.

There's also one more random crash/hang that I'm aware of that happens due to a bug in toolbox that has been fixed but not released yet.

**Comment by FromTheGrayve** [comment] 2024-04-28 06:25
Oh, nice to see a fast reply and ongoing development.  I haven't had a crash since my post, but it has had a severe stutter in combat a few times where I thought it was about to. 

The only thing i changed was the tool box setting to 'show special allies on the party list' , but the crashing is random so it might just be luck. if i notice anything more ill share it.

**Comment by AlexMacocian** [comment] 2024-04-28 06:32
Yeah, the crash caused by the Daybreak plugin is completely random and super hard to trigger :/. 

In regards to the stutter, could you try going into memory reader settings and set the memory reader frequency to have a higher delay? Like iirc by default is 16ms. Try to go to 100+?

I think the stutters happen when there's a lot of things going on and Daybreak requests start to make the game stutter.

**Comment by FromTheGrayve** [comment] 2024-04-28 09:49
It was at the default of what i assume is 0, i've upped it to 20

**Comment by AlexMacocian** [comment] 2024-04-28 09:55
Oh right. 0 means that it'll spam GW as often as it can. 20 means it will cache responses for 20ms, so that subsequent requests don't spam GW in that 20ms window.

If you notice heavy stuttering, I'd increase this even more

**Comment by Ezelbys** [comment] 2024-04-28 17:20
Hi,
I found a crash that sound eerily similar while both focus mode and gwtoolbox are activated. The catch is that it is easily triggerable.
You go into an explorable zone with party members, and you double click on one of your party members. The game should hang and crash.
The current workaround is the same :  to either disable focus or GWToolbox.

**Comment by Ezelbys** [comment] 2024-04-28 17:31
https://youtu.be/wacsUrUSmW4
Video showcasing it

**Comment by AlexMacocian** [comment] 2024-04-28 17:39
Ah yeah this particular one is a bug in toolbox that has been fixed but not yet released. Once toolbox Devs release the new version, this particular crash should be fixed

**Comment by FromTheGrayve** [comment] 2024-04-28 21:20
I upped the memory to 30ms and havent' had a crash since. Not sure if its luck or an actual fix.

**Comment by FromTheGrayve** [comment] 2024-04-29 09:20
This may be the same bug as the Toolbox issue, but just in cast its not:  

If i am carrying an item, andtarget an enemy, and hit spacebar, the game freezes. 

I can target an ally/friendly NPC at it works fine.

**Comment by AlexMacocian** [comment] 2024-04-29 09:45
Can you try to reproduce it without toolbox running?

**Comment by FromTheGrayve** [comment] 2024-04-30 11:08
I can definetly reproduce it.

**Comment by AlexMacocian** [comment] 2024-04-30 12:35
Okay that's really interesting. Thanks for letting me know

**Comment by AlexMacocian** [comment] 2024-05-01 09:05
I can reproduce it as well. It seems to be another bug in GWCA (the core toolbox module). I'll talk with the devs to come up with a fix

**Comment by AlexMacocian** [comment] 2024-05-01 09:14
Bug was fixed in the lastest version of GWCA. It's going to be part of the next release of GWToolbox and Daybreak

**Comment by AlexMacocian** [comment] 2024-05-01 09:23
@FromTheGrayve @Ezelbys I think your issues should be fixed now in Daybreak. Toolbox might still be causing that targeting crash until the update, but that's also coming pretty soon.

I'm releasing the new version now. Please update whenever you can and let me know if you still see issues

**Closed** 2024-05-01 09:35 UTC
Labels: bug

**Comment by FromTheGrayve** [comment] 2024-05-01 10:41
Glad it was fixed!
